// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "trace.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tentropy {

namespace {

const ::google::protobuf::Descriptor* CryptoTrace_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CryptoTrace_reflection_ = NULL;
const ::google::protobuf::Descriptor* CryptoTrace_MemAccess_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CryptoTrace_MemAccess_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_trace_2eproto() {
  protobuf_AddDesc_trace_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "trace.proto");
  GOOGLE_CHECK(file != NULL);
  CryptoTrace_descriptor_ = file->message_type(0);
  static const int CryptoTrace_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CryptoTrace, start_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CryptoTrace, end_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CryptoTrace, write_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CryptoTrace, read_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CryptoTrace, code_),
  };
  CryptoTrace_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CryptoTrace_descriptor_,
      CryptoTrace::default_instance_,
      CryptoTrace_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CryptoTrace, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CryptoTrace, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CryptoTrace));
  CryptoTrace_MemAccess_descriptor_ = CryptoTrace_descriptor_->nested_type(0);
  static const int CryptoTrace_MemAccess_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CryptoTrace_MemAccess, addr_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CryptoTrace_MemAccess, data_),
  };
  CryptoTrace_MemAccess_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CryptoTrace_MemAccess_descriptor_,
      CryptoTrace_MemAccess::default_instance_,
      CryptoTrace_MemAccess_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CryptoTrace_MemAccess, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CryptoTrace_MemAccess, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CryptoTrace_MemAccess));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_trace_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CryptoTrace_descriptor_, &CryptoTrace::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CryptoTrace_MemAccess_descriptor_, &CryptoTrace_MemAccess::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_trace_2eproto() {
  delete CryptoTrace::default_instance_;
  delete CryptoTrace_reflection_;
  delete CryptoTrace_MemAccess::default_instance_;
  delete CryptoTrace_MemAccess_reflection_;
}

void protobuf_AddDesc_trace_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013trace.proto\022\010tentropy\"\340\001\n\013CryptoTrace\022"
    "\r\n\005start\030\001 \002(\004\022\013\n\003end\030\002 \002(\004\022.\n\005write\030\003 \003"
    "(\0132\037.tentropy.CryptoTrace.MemAccess\022-\n\004r"
    "ead\030\004 \003(\0132\037.tentropy.CryptoTrace.MemAcce"
    "ss\022-\n\004code\030\005 \003(\0132\037.tentropy.CryptoTrace."
    "MemAccess\032\'\n\tMemAccess\022\014\n\004addr\030\001 \002(\004\022\014\n\004"
    "data\030\002 \002(\014", 250);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "trace.proto", &protobuf_RegisterTypes);
  CryptoTrace::default_instance_ = new CryptoTrace();
  CryptoTrace_MemAccess::default_instance_ = new CryptoTrace_MemAccess();
  CryptoTrace::default_instance_->InitAsDefaultInstance();
  CryptoTrace_MemAccess::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_trace_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_trace_2eproto {
  StaticDescriptorInitializer_trace_2eproto() {
    protobuf_AddDesc_trace_2eproto();
  }
} static_descriptor_initializer_trace_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CryptoTrace_MemAccess::kAddrFieldNumber;
const int CryptoTrace_MemAccess::kDataFieldNumber;
#endif  // !_MSC_VER

CryptoTrace_MemAccess::CryptoTrace_MemAccess()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tentropy.CryptoTrace.MemAccess)
}

void CryptoTrace_MemAccess::InitAsDefaultInstance() {
}

CryptoTrace_MemAccess::CryptoTrace_MemAccess(const CryptoTrace_MemAccess& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:tentropy.CryptoTrace.MemAccess)
}

void CryptoTrace_MemAccess::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  addr_ = GOOGLE_ULONGLONG(0);
  data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CryptoTrace_MemAccess::~CryptoTrace_MemAccess() {
  // @@protoc_insertion_point(destructor:tentropy.CryptoTrace.MemAccess)
  SharedDtor();
}

void CryptoTrace_MemAccess::SharedDtor() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (this != default_instance_) {
  }
}

void CryptoTrace_MemAccess::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CryptoTrace_MemAccess::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CryptoTrace_MemAccess_descriptor_;
}

const CryptoTrace_MemAccess& CryptoTrace_MemAccess::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_trace_2eproto();
  return *default_instance_;
}

CryptoTrace_MemAccess* CryptoTrace_MemAccess::default_instance_ = NULL;

CryptoTrace_MemAccess* CryptoTrace_MemAccess::New() const {
  return new CryptoTrace_MemAccess;
}

void CryptoTrace_MemAccess::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    addr_ = GOOGLE_ULONGLONG(0);
    if (has_data()) {
      if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        data_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CryptoTrace_MemAccess::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tentropy.CryptoTrace.MemAccess)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 addr = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &addr_)));
          set_has_addr();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_data;
        break;
      }

      // required bytes data = 2;
      case 2: {
        if (tag == 18) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tentropy.CryptoTrace.MemAccess)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tentropy.CryptoTrace.MemAccess)
  return false;
#undef DO_
}

void CryptoTrace_MemAccess::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tentropy.CryptoTrace.MemAccess)
  // required uint64 addr = 1;
  if (has_addr()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->addr(), output);
  }

  // required bytes data = 2;
  if (has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->data(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:tentropy.CryptoTrace.MemAccess)
}

::google::protobuf::uint8* CryptoTrace_MemAccess::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tentropy.CryptoTrace.MemAccess)
  // required uint64 addr = 1;
  if (has_addr()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->addr(), target);
  }

  // required bytes data = 2;
  if (has_data()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->data(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tentropy.CryptoTrace.MemAccess)
  return target;
}

int CryptoTrace_MemAccess::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint64 addr = 1;
    if (has_addr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->addr());
    }

    // required bytes data = 2;
    if (has_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->data());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CryptoTrace_MemAccess::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CryptoTrace_MemAccess* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CryptoTrace_MemAccess*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CryptoTrace_MemAccess::MergeFrom(const CryptoTrace_MemAccess& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_addr()) {
      set_addr(from.addr());
    }
    if (from.has_data()) {
      set_data(from.data());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CryptoTrace_MemAccess::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CryptoTrace_MemAccess::CopyFrom(const CryptoTrace_MemAccess& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CryptoTrace_MemAccess::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void CryptoTrace_MemAccess::Swap(CryptoTrace_MemAccess* other) {
  if (other != this) {
    std::swap(addr_, other->addr_);
    std::swap(data_, other->data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CryptoTrace_MemAccess::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CryptoTrace_MemAccess_descriptor_;
  metadata.reflection = CryptoTrace_MemAccess_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int CryptoTrace::kStartFieldNumber;
const int CryptoTrace::kEndFieldNumber;
const int CryptoTrace::kWriteFieldNumber;
const int CryptoTrace::kReadFieldNumber;
const int CryptoTrace::kCodeFieldNumber;
#endif  // !_MSC_VER

CryptoTrace::CryptoTrace()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tentropy.CryptoTrace)
}

void CryptoTrace::InitAsDefaultInstance() {
}

CryptoTrace::CryptoTrace(const CryptoTrace& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:tentropy.CryptoTrace)
}

void CryptoTrace::SharedCtor() {
  _cached_size_ = 0;
  start_ = GOOGLE_ULONGLONG(0);
  end_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CryptoTrace::~CryptoTrace() {
  // @@protoc_insertion_point(destructor:tentropy.CryptoTrace)
  SharedDtor();
}

void CryptoTrace::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CryptoTrace::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CryptoTrace::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CryptoTrace_descriptor_;
}

const CryptoTrace& CryptoTrace::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_trace_2eproto();
  return *default_instance_;
}

CryptoTrace* CryptoTrace::default_instance_ = NULL;

CryptoTrace* CryptoTrace::New() const {
  return new CryptoTrace;
}

void CryptoTrace::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<CryptoTrace*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(start_, end_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  write_.Clear();
  read_.Clear();
  code_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CryptoTrace::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tentropy.CryptoTrace)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 start = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &start_)));
          set_has_start();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_end;
        break;
      }

      // required uint64 end = 2;
      case 2: {
        if (tag == 16) {
         parse_end:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &end_)));
          set_has_end();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_write;
        break;
      }

      // repeated .tentropy.CryptoTrace.MemAccess write = 3;
      case 3: {
        if (tag == 26) {
         parse_write:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_write()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_write;
        if (input->ExpectTag(34)) goto parse_read;
        break;
      }

      // repeated .tentropy.CryptoTrace.MemAccess read = 4;
      case 4: {
        if (tag == 34) {
         parse_read:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_read()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_read;
        if (input->ExpectTag(42)) goto parse_code;
        break;
      }

      // repeated .tentropy.CryptoTrace.MemAccess code = 5;
      case 5: {
        if (tag == 42) {
         parse_code:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_code()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_code;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tentropy.CryptoTrace)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tentropy.CryptoTrace)
  return false;
#undef DO_
}

void CryptoTrace::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tentropy.CryptoTrace)
  // required uint64 start = 1;
  if (has_start()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->start(), output);
  }

  // required uint64 end = 2;
  if (has_end()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->end(), output);
  }

  // repeated .tentropy.CryptoTrace.MemAccess write = 3;
  for (int i = 0; i < this->write_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->write(i), output);
  }

  // repeated .tentropy.CryptoTrace.MemAccess read = 4;
  for (int i = 0; i < this->read_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->read(i), output);
  }

  // repeated .tentropy.CryptoTrace.MemAccess code = 5;
  for (int i = 0; i < this->code_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->code(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:tentropy.CryptoTrace)
}

::google::protobuf::uint8* CryptoTrace::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tentropy.CryptoTrace)
  // required uint64 start = 1;
  if (has_start()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->start(), target);
  }

  // required uint64 end = 2;
  if (has_end()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->end(), target);
  }

  // repeated .tentropy.CryptoTrace.MemAccess write = 3;
  for (int i = 0; i < this->write_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->write(i), target);
  }

  // repeated .tentropy.CryptoTrace.MemAccess read = 4;
  for (int i = 0; i < this->read_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->read(i), target);
  }

  // repeated .tentropy.CryptoTrace.MemAccess code = 5;
  for (int i = 0; i < this->code_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->code(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tentropy.CryptoTrace)
  return target;
}

int CryptoTrace::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint64 start = 1;
    if (has_start()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->start());
    }

    // required uint64 end = 2;
    if (has_end()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->end());
    }

  }
  // repeated .tentropy.CryptoTrace.MemAccess write = 3;
  total_size += 1 * this->write_size();
  for (int i = 0; i < this->write_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->write(i));
  }

  // repeated .tentropy.CryptoTrace.MemAccess read = 4;
  total_size += 1 * this->read_size();
  for (int i = 0; i < this->read_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->read(i));
  }

  // repeated .tentropy.CryptoTrace.MemAccess code = 5;
  total_size += 1 * this->code_size();
  for (int i = 0; i < this->code_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->code(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CryptoTrace::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CryptoTrace* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CryptoTrace*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CryptoTrace::MergeFrom(const CryptoTrace& from) {
  GOOGLE_CHECK_NE(&from, this);
  write_.MergeFrom(from.write_);
  read_.MergeFrom(from.read_);
  code_.MergeFrom(from.code_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_start()) {
      set_start(from.start());
    }
    if (from.has_end()) {
      set_end(from.end());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CryptoTrace::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CryptoTrace::CopyFrom(const CryptoTrace& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CryptoTrace::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->write())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->read())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->code())) return false;
  return true;
}

void CryptoTrace::Swap(CryptoTrace* other) {
  if (other != this) {
    std::swap(start_, other->start_);
    std::swap(end_, other->end_);
    write_.Swap(&other->write_);
    read_.Swap(&other->read_);
    code_.Swap(&other->code_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CryptoTrace::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CryptoTrace_descriptor_;
  metadata.reflection = CryptoTrace_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace tentropy

// @@protoc_insertion_point(global_scope)
